# Introduction to tensor

In [2]:
import tensorflow as tf
print(tf.__version__)

2.13.0


Creating a tensor using tf.constant


In [3]:
scaler = tf.constant(7)
scaler

# scaler has dimension as 0

<tf.Tensor: shape=(), dtype=int32, numpy=7>

Checking dimension of tensor

In [4]:
scaler.ndim

0

In [5]:
vector = tf.constant([10,13])
vector

# vector has dimension as 1

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 13], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
matrix = tf.constant([[10,11],[12,13]])
matrix

# matrix is nothing but 2 dimensional array

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 11],
       [12, 13]], dtype=int32)>

In [8]:
matrix.ndim

2

creating tensor using tf.variable

Tensors created using tf.constant are immutable while those created using tf.variable are mutable and their value can be changes using assign() method

In [9]:
tensor = tf.Variable([10,7])
tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

Creating random tensors

In [10]:
random_tensor = tf.random.uniform(minval=1,maxval=100,shape=(2,2),dtype=tf.int32)
random_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[99, 84],
       [76, 98]], dtype=int32)>

Different types of tensors

In [12]:
# tensor of all ones
tf.ones(shape=(3,3),dtype=tf.float16)


<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float16)>

In [13]:
# tensor of all zeros
tf.zeros(shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [19]:
# indentity matrix
identity_matrix = tf.eye(5)
print(identity_matrix)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
