## Tensors using NumPy arrays

The main difference between numpy array and tensors is that later can be run on GPU for faster numerical computing

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
numpy_A = np.arange(1,25,dtype = np.int32)
type(numpy_A)

numpy.ndarray

In [4]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [5]:
B = tf.constant(numpy_A ,shape = (8,3))
B

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

Basic attributes of tensors
1. Shape:- it gives the number of elements present in each of the dimension of the tensor ,for example: shape = [2,3] denotes that there are 2 elements(number of rows) and there are 3 columns in each of the dimension
2. size:- It gives the number of elements present in the tensor i.e count

In [6]:
attributes_of_tensor = tf.ones(shape=(2,3,4,5),dtype=tf.int32)
attributes_of_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]], dtype=int32)>

In [7]:
attributes_of_tensor.shape

TensorShape([2, 3, 4, 5])

In [8]:
tf.size(attributes_of_tensor)
# output 120 means that there are total 120 values in each of the axis of tensor

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [9]:
attributes_of_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)>

Indexing of tensors

In [10]:
# getting first 2 elements of each dimension
attributes_of_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]], dtype=int32)>

In [11]:
# getting the first element from each dimension from each index except for the final one
attributes_of_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[1, 1, 1, 1, 1]]]], dtype=int32)>

In [12]:
# adding extra dimension to a tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [13]:
rank_2_tensor.ndim

2

In [14]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [15]:
rank_4_tensor = rank_3_tensor[...,tf.newaxis]

In [16]:
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]], dtype=int32)>

In [17]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # axis = -1 mean add another dimension after the previous last dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [18]:
tf.expand_dims(rank_2_tensor,axis=0) #adding at the start

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

Manipulating tensors(tensor operations)
1. **Basic Operations**
 `+` , `-` ,`*`  
2. When manipulating tensor the original remains unchanged

In [19]:
# addition
tensor = tf.constant([[10,7],[3,4]])
tensor + 10 # this will add 10 to each value


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [20]:
tensor #original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [21]:
# multiplication
tensor2 = tf.constant([[1,1],[2,2]])
tensor2 *2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [4, 4]], dtype=int32)>

In [22]:
# division
tensor3 = tf.constant([[10,10],[5,5]])
tensor3//5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [1, 1]], dtype=int32)>

Another way to manipulate the tensors is using inbuilt tensorflow functions like
1. tf.multiply(`tensor name` , `value`)
2. tf.add() and so on

Matrix Multiplication

**Rules for tensor(matrix) multiplication**
1. The inner dimensions must match i.e if 3 x 2 and 3 x 2 here the inner dimensions are different (2,3) therefor it will give error
2. The resulting matrix has the shape of the outer dimension

In [23]:
tensor2 , tensor3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 10],
        [ 5,  5]], dtype=int32)>)

In [24]:
tensor_multplication = tf.matmul(tensor2,tensor3)
tensor_multplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 15],
       [30, 30]], dtype=int32)>

In [25]:
tensor3= tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor4 = tf.constant([[3,5],[6,7],[1,8]])

result_tensor = tf.matmul(tensor3,tensor4)
print(result_tensor)

tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


**Dot Product**

Dot product is same as matrix multiplication. This can be performed using
1. `tf.matmul()`
2. `tf.tensordot()`

In [26]:
# dot product requires either of the tensor(matrix) to be in transpose
tensor3 , tensor4

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [28]:
tf.tensordot(tf.transpose(tensor3) , tensor4 ,axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48],
       [24, 56]], dtype=int32)>