## Tensors using NumPy arrays

The main difference between numpy array and tensors is that later can be run on GPU for faster numerical computing

In [81]:
import numpy as np
import tensorflow as tf

In [82]:
numpy_A = np.arange(1,25,dtype = np.int32)
type(numpy_A)

numpy.ndarray

In [83]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [84]:
B = tf.constant(numpy_A ,shape = (8,3))
B

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])>

Basic attributes of tensors
1. Shape:- it gives the number of elements present in each of the dimension of the tensor ,for example: shape = [2,3] denotes that there are 2 elements(number of rows) and there are 3 columns in each of the dimension
2. size:- It gives the number of elements present in the tensor i.e count

In [85]:
attributes_of_tensor = tf.ones(shape=(2,3,4,5),dtype=tf.int32)
attributes_of_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]],


       [[[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1]]]])>

In [86]:
attributes_of_tensor.shape

TensorShape([2, 3, 4, 5])

In [87]:
tf.size(attributes_of_tensor)
# output 120 means that there are total 120 values in each of the axis of tensor

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [88]:
attributes_of_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=int32, numpy=
array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])>

Indexing of tensors

In [89]:
# getting first 2 elements of each dimension
attributes_of_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1]]]])>

In [90]:
# getting the first element from each dimension from each index except for the final one
attributes_of_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[1, 1, 1, 1, 1]]]])>

In [91]:
# adding extra dimension to a tensor
rank_2_tensor = tf.constant([[10,7],[3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [92]:
rank_2_tensor.ndim

2

In [93]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [94]:
rank_4_tensor = rank_3_tensor[...,tf.newaxis]

In [95]:
rank_4_tensor

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]])>

In [96]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # axis = -1 mean add another dimension after the previous last dimension

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [97]:
tf.expand_dims(rank_2_tensor,axis=0) #adding at the start

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

Manipulating tensors(tensor operations)
1. **Basic Operations**
 `+` , `-` ,`*`  
2. When manipulating tensor the original remains unchanged

In [98]:
# addition
tensor = tf.constant([[10,7],[3,4]])
tensor + 10 # this will add 10 to each value


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [99]:
tensor #original tensor remains unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [100]:
# multiplication
tensor2 = tf.constant([[1,1],[2,2]])
tensor2 *2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [4, 4]])>

In [101]:
# division
tensor3 = tf.constant([[10,10],[5,5]])
tensor3//5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [1, 1]])>

Another way to manipulate the tensors is using inbuilt tensorflow functions like
1. tf.multiply(`tensor name` , `value`)
2. tf.add() and so on

Matrix Multiplication

**Rules for tensor(matrix) multiplication**
1. The inner dimensions must match i.e if 3 x 2 and 3 x 2 here the inner dimensions are different (2,3) therefor it will give error
2. The resulting matrix has the shape of the outer dimension

In [102]:
tensor2 , tensor3

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 10],
        [ 5,  5]])>)

In [103]:
tensor_multplication = tf.matmul(tensor2,tensor3)
tensor_multplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[15, 15],
       [30, 30]])>

In [104]:
tensor3= tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor4 = tf.constant([[3,5],[6,7],[1,8]])

result_tensor = tf.matmul(tensor3,tensor4)
print(result_tensor)

tf.Tensor(
[[20 59]
 [34 57]
 [30 60]], shape=(3, 2), dtype=int32)


**Dot Product**

Dot product is same as matrix multiplication. This can be performed using
1. `tf.matmul()`
2. `tf.tensordot()`

In [105]:
# dot product requires either of the tensor(matrix) to be in transpose
tensor3 , tensor4

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [106]:
tf.tensordot(tf.transpose(tensor3) , tensor4 ,axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48],
       [24, 56]])>

Aggregating Tnesor

In [107]:
# Getting the absoulte value
D = tf.constant([-10,-3])
print(D)
print(tf.abs(D))

tf.Tensor([-10  -3], shape=(2,), dtype=int32)
tf.Tensor([10  3], shape=(2,), dtype=int32)


In [108]:
# Getting the minimum, maxium, sum ,mean  value
E = tf.constant(np.random.randint(0,200,size=50))
tf.size(E)
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 10,   2, 107, 194,  68,   3, 172, 124,  10,  95, 117,  54,  97,
        25,  18,  75, 134,  95, 138,  76, 142,  59, 184, 177,  61, 101,
        38,  71, 153,   7,  85,  68,  66,  42,  92,   1,  28, 100, 174,
       105, 181,  10,  80, 150,  36,  10, 184,   0, 142,  84])>

In [109]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [110]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=194>

In [111]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=4245>

In [112]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=84>

In [113]:
# to find varinace and standard deviation we need to import tensorflow_probability. tensorflows has math and probability modules which are different
import tensorflow_probability as tfp
tfp.stats.variance(E)
# look for documentation for more details

ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.14; Detected an installation of version 2.13.0. Please upgrade TensorFlow to proceed.

In [115]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=3346.85>

In [116]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=57.851967>

Finding positional maximum and minimum


In [117]:
# creating a new tensor for finding positional maximum and minimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [119]:
# positional maximum
tf.argmax(F)  # it gives the index at which the maximum value is present

# position minimum
tf.argmin(F)  # it gives the index at which the minimum value is present

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [122]:
print(F[tf.argmax(F)])
print(tf.reduce_max(F))
print(F[tf.argmin(F)])
print(tf.reduce_min(F))

tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(0.009463668, shape=(), dtype=float32)
tf.Tensor(0.009463668, shape=(), dtype=float32)


Squeezing a tensor . Removing all single dinmensions 

In [126]:
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [127]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [128]:
# removes dimesnion of size 1 from the tensor 
G_squeezed = tf.squeeze(G)
G_squeezed.shape , G.shape

(TensorShape([50]), TensorShape([1, 1, 1, 1, 50]))

### ONE HOT ENCODING TENSORS 

In [137]:
set_list = [0,1,2,3]
tf.one_hot(set_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [139]:
# specifying custom values for one hot encoding 
tf.one_hot(set_list,depth=4,on_value='X',off_value='0')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'X', b'0', b'0', b'0'],
       [b'0', b'X', b'0', b'0'],
       [b'0', b'0', b'X', b'0'],
       [b'0', b'0', b'0', b'X']], dtype=object)>

### TENSORS CAN ALSO BE CREATED USING NUMPY 

AND THEY CAN ALSO BE CONVERTED INTO EACH OTHER EASILY 

In [140]:
tf.config.list_logical_devices

<function tensorflow.python.framework.config.list_logical_devices(device_type=None)>

### COMMANDS TO CHECK DEVICE USAGE AND GPU USAGE 
1. `tf.config.lits_physical_devices` :-  is used to list all the physical devices of the system that are avialable 
2. `!nvidia-smi` :-  is used to get GPU infirmation. can be used only GPU drivers are installed